### ISSUE TITLE
OrderEntry: OrderDetails popover component

### ISSUE THREAD

**Issue by battaile** [battaile/dashboard-redux#23]
>Looking further at the document as it exists with no items we see that opening the details window next to the order number field reveals a pop-over with the following information. Note that many of these fields cannot be edited regardless of permissions.  Email address is going to take special consideration but for now should also not be editable.  Saving this window commits any changes, canceling just closes the window without any changes to data.

phase1 requirement: fully functional, read only

**Comment by battaile** [comment]
I want to have a chat with Jason about this before proceeding.  It looks like the only field it displays that isn't viewable on the main screen is price level.

**Comment by battaile** [comment]
Decided to go ahead and implement as described as JR is in Albany.  Can see the value in having a dedicated area to edit those fields, even if we're not adding new ones.  This component is in place with order being passed in as props, just needs to be fleshed out.

**Comment by ajkagy** [comment]
Added fields/formatting. Still missing Level and Origin props.

**Comment by battaile** [comment]
@ajkagy can you make status use something other than a button, having a clickable element displaying that data seems odd
